//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slavasRabota
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogisTransEntities1 : DbContext
    {
        public LogisTransEntities1()
            : base("name=LogisTransEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatuses> OrderStatuses { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Routess> Routess { get; set; }
        public virtual DbSet<RouteStatuses> RouteStatuses { get; set; }
        public virtual DbSet<Sotrudnikis> Sotrudnikis { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
        public virtual DbSet<TransportSostoyanie> TransportSostoyanie { get; set; }
    }
}
