//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slavasRabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Routess = new HashSet<Routess>();
        }
    
        public int ID_Order { get; set; }
        public int Client_ID { get; set; }
        public string GruzName { get; set; }
        public Nullable<int> GruzWeight { get; set; }
        public string DateOtpravki { get; set; }
        public string DateDostavki { get; set; }
        public int OrderStatus_ID { get; set; }
        public int Storage_ID { get; set; }
        public Nullable<decimal> SumOplati { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual Storage Storage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Routess> Routess { get; set; }
    }
}
