//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slavasRabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnikis
    {
        public int ID_Sotrudnik { get; set; }
        public string SotrudnikName { get; set; }
        public string SotrudnikSurname { get; set; }
        public string SotrudnikMiddleName { get; set; }
        public string PhoneNumber { get; set; }
        public string Loginn { get; set; }
        public string Passwordd { get; set; }
        public int Role_ID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
